language: java

addons:
  sonarcloud:
    organization: "dumb-code"
    token:
      secure: "jT0N5ekeiqr/KzBeL524T/RYmishMvbohxelM1sv4/0ckMckZ1hvXy/onpz45d2cizLI1yxNDfNDP3YM6nlj3r0hlBgxt/pKMCcfoqVyBPlglSUPLsq6YeRXsBC37Ut8+kF8lZ70rKd30KPhCWKH208SnrcmU9ijNshnN+Jl5OCDhwum6yS6bI0FTrp6wYCZqUGXtzDEAGuihZKBqxhprQm3ZAZlTv+Gd/aekzZ/s5wkYD7z8zpwOXUVkWdrH/lRC0TeKPvAxsmQE92EmpHSM24OluSRevvNvok0+9Yz3/7McHca/8rlnLn4Qdwi90lHOilbkyXdcWM5M++D3hLYg4FlCn6gXBJ7HyU2PSRMo3DDTLXLQeo6nBwvMiGGp5F8weqr05xf6uYB/Be9UDIIg1eEvR4jUdoIh2Uw1StCo0sXI6y8nBkUc/Lpi715uV8HK7cpLXBRSs8hlYPBykcPG1lqKTpqPSJlzgNB+LaukZWM/+jlWvsiBlDqZmexmU6n1nFWSc6lixSJjBks8lvlVIrDpVkIRPnWiW+157mLV7KZ1gs3vyohwm3y9CwP2i/BiY7+9V37SP/EZJwbfzAHNOYxvpuxRFaFUT8TAjtulY2V+MI0m57W0s/jNTq44mhAp0GmXO83whSpptaUQJbqWPLVAlH4gBfKXzstDD43ggM="
jdk:
  - oraclejdk8

install:
  - true

script:
  - "./gradlew sonarqube"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'